[tool.poetry]
name = "SiteSync"
version = "1.0.0"
description = "SiteSync Addon"
authors = ["OpenPype Team <info@openpype.io>"]
license = "MIT License"
homepage = "https://openpype.io"
documentation = "https://openpype.io/docs/artist_getting_started"
repository = "https://github.com/pypeclub/openpype"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7"
aiohttp-middlewares = "^2.0.0"
dropbox = "^11.20.0"
google-api-python-client = "^1.12.8" # sync server google support (should be separate?)
pywin32 = { version = "301", markers = "sys_platform == 'win32'" }
pysftp = "^0.2.9"
wsrpc_aiohttp = "^3.1.1" # websocket server


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[openpype]

exclude = [
    "**/node_modules",
    "**/__pycache__"
]
